In [2]:
x_int = 3   #revision of last lesson
x_float = 3.  #revision of last lesson
x_string = 'three' #revision of last lesson
x_list = [3, 'three']  #this is the new thing
print(type(x_int))
print(type(x_float))
print(type(x_string))
print(type(x_list))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>


# NUMPY

In [1]:
import numpy as np
print ('NumPy:', np.__version__)

NumPy: 1.18.5


### Creating Arrays

In [28]:
mylist = (1,2,3,4,5,6,7,8,9)
my1darr= np.array(mylist)
print(type(my1darr))
my1darr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my2darr=np.array([[1,2,3],[4,5,6],[7,8,9]])
my2darr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
my3darr = np.array([  [[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]  ])
my3darr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [31]:
# Shape using `.shape`
print(my1darr.shape)
print(my2darr.shape)
print(my3darr.shape)

# Shape using `np.shape()`
print(np.shape(my1darr))
print(np.shape(my2darr))
print(np.shape(my3darr))

(9,)
(3, 3)
(3, 3, 1)
(9,)
(3, 3)
(3, 3, 1)


In [32]:
# Create a list with floats and strings
lst = [1., 'cat']
print(lst)

# Create a numpy array from a list with mixed data types
arr = np.array(lst)
print(arr)

# The data type of the 1. in the list is the same data type than the 1. in the array?
print(f"Type list = type array? {((lst[0])) == type((arr[0]))}")
print(f"Type list: {type(lst[0])}")
print(f"Type array: {type(arr[0])}")

[1.0, 'cat']
['1.0' 'cat']
Type list = type array? False
Type list: <class 'float'>
Type array: <class 'numpy.str_'>


## Special Arrays
There are some functionalities that allow us to create arrays filled with determined values. ones and zeros provide arrays of the given shape and type (default is float64), filled with ones or zeros, respectively.

In [6]:
#To create a 0-filled array of size 3x2
np.zeros?
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
#To create a one-filled numpy array of 3x2x4 - meaning there are 3 2x4 arrays
np.ones?
np.ones((2,3,2,4)) # i added another two to see if we could duplicate it and yes we can

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [34]:
mylist = (1,2,3,4,5,6,7,8,9)
my1darr= np.array(mylist)
print(type(my1darr))
my1darr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#to create a 1-filled numpy array but with the 1s being diagonal7

print(np.eye(5, k=2))#k pushes the 1s up by the number of columns specified after it
print(np.eye(5, k=-2)) #writing mnus pushes the 1s down
np.diag(my1darr,1) #the second entry makes the array of a list start diagonally after one column

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
# To create an array with a range starting at 0, and stopping before 16
myrange = np.arange(0, 16)
myrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
%timeit np.arange(0, 2000000, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

In [41]:
np.arange(1, 1000000, 2)

array([     1,      3,      5, ..., 999995, 999997, 999999])

In [50]:
list(i for i in range(2000000) if i % 2 == 1) #this would make it a list
type([i for i in range(2000000) if i % 2 == 0]) #does the same without specifying it to be a list

list

In [51]:
%timeit np.arange(0, 2000000, 2)

%timeit [i for i in range(2000000) if i % 2 == 0]

2.5 ms ± 74.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
271 ms ± 9.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
