# Numpy tutorial on Youtube - 21 min

### https://www.youtube.com/watch?v=AAS8yoKuK7M&ab_channel=JoeJames

in case you dont have: use pip install numpy

In [2]:
import numpy as np

Let's create an array
* Pass in a list to the array() constructor
* Use the arrange function, similar to the range function but used for Numpy arrays. Uses the arguments (start, stop+1, step).
* Use linspace to create an array of n equally spaced values. Uses arguments (start, stop, number of items)
* Create an array empty, full of ones or zeros, or full of any fil value. Uses argument (shape) in the form of a tuple.

In [26]:
a = np.array([1,3,5,7,9,11]) #array constructor
print(a)

a= np.arange(1,12,2) #creating a range-like array from 1-11 in increments of 2
print(a)

a= np.linspace(5,8,13) #linear spacing- controlled number of items. Instead of setting increments, you specify the number of outcomes. so we go from 5- 8 in increments that result in 13 elements
print(a)

a=np.zeros((4,2)) #an array full of zeroes with dimensions we have specified. 
print(a)

a= np.ones((2,3), dtype=np.int16) #same as above but for ones plus we set the data type- int16 is a defined data type.
print(a)

a=np.full((6,), 88) #a one-dimensional array with a defined number of a given element
print(a)

a=np.fromstring('25 0 35 40', dtype=np.int, sep=' ') #we enter string, separate by spaces that we specify with sep=' ', convert to dtype = integer type that numpy decides
print(a)

a=np.array([[1,3,5],[7,8,9]]) #two dimensional array
print(a)

b=np.zeros_like(a) #creates a similar array to specified one and fills it in with zeros
print(b)

c=np.ones_like(a) #same but for ones
print(c)

d=np.ones_like(b) #works regardless of content of reference array
print(d)

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]
[5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75 8.  ]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 1 1]
 [1 1 1]]
[88 88 88 88 88 88]
[25  0 35 40]
[[1 3 5]
 [7 8 9]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


## Numpy Attributes
learning about the characteristics of a given array

In [36]:
print(a)
print(a.size)
print(a.shape) #output is 2 rows by 3 columns
print(a.ndim) #number of dimensions- 2
print(a.itemsize) #the memory each item takes up in an array (each item is same type)
print(a.dtype) #type of data- int32 takes up 4bytes for every item. 
print(a.nbytes) #total memory used by all items in the array. 4bytes*6items
a.nbytes==(a.size*a.itemsize) #same thing

[[1 3 5]
 [7 8 9]]
6
(2, 3)
2
4
int32
24


True

## Indexing and Slicing

Use square brckets to get an array by index. Multidimensional arrays can use multiple square brackets embedded in one another.

There are three arguments for slicing arrays, all are optional: [stat:stop:step].
If start is left blank, it defaults to 0
If stop is left blank, it defaults to the end of the array
Step defaults to 1

In [47]:
print(a)
print(a[1])
print(a[0][2])#from the 0th item get the 2nd item 
print(c[1:4]) #wont get output beyond 1st item cuz we dont have those dimensions

print(a[:1]) #slices after first item
print(a[1:3:2])
print(a[:, 1:2]) #slices, square bracket for the whole array, colon for x dimension, 

[[1 3 5]
 [7 8 9]]
[7 8 9]
5
[[1 1 1]]
[[1 3 5]]
[[7 8 9]]
[[3]
 [8]]


## Reshape, Swap, Axes, Flatten
array manipulation routines

In [51]:
e = np.arange(-9, -3,).reshape(2,3) #arange that inputs range into an array of defined dimensions
print(e)

e= e.swapaxes(0,1)
print(e)

e=e.flatten()
print(e)



[[-9 -8 -7]
 [-6 -5 -4]]
[[-9 -6]
 [-8 -5]
 [-7 -4]]
[-9 -6 -8 -5 -7 -4]


## Using dtype to Save Space
default data types- int32 and float64, are memory hogs. If you dont need higher precision, you can save a lot of memory space and improve operation speed using smaller data types. Makes a big difference for larger data sets.
Use a dtype that makes sense for the type of data that you store

In [52]:
f=np.arange(0,100) #we made a 100 element array
print(f.dtype, type(d[1]))
print(f.nbytes) #number of bytes

f=np.arange(0,100, dtype='int8') #if we arent using like 10 digit integers, then we use int8
print(f.dtype, type(d[1]))
print(f.nbytes)

int32 <class 'numpy.ndarray'>
400
int8 <class 'numpy.ndarray'>
100


## UpCasting, Rounding, Print Formatting
Data type of all items is upcast to the most precise element

In [75]:
g=np.array([(1.566666,2,3),(4,5,6)])
print(g)
print(g.dtype)

g=g.round(4)
print(g)

np.set_printoptions(precision=5,suppress=True)
print(g)
np.set_printoptions(precision=None,suppress=False)
print(g)

[[1.56667 2.      3.     ]
 [4.      5.      6.     ]]
float64
[[1.5667 2.     3.    ]
 [4.     5.     6.    ]]
[[1.5667 2.     3.    ]
 [4.     5.     6.    ]]
[[1.5667 2.     3.    ]
 [4.     5.     6.    ]]


## Numpy Data Types Available
unit is unsigned int, for positive numbers

In [76]:
import pprint as pp #pretty print
pp.pprint(np.sctypes) #all available data types for numpy arrays

{'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>],
 'float': [<class 'numpy.float16'>,
           <class 'numpy.float32'>,
           <class 'numpy.float64'>],
 'int': [<class 'numpy.int8'>,
         <class 'numpy.int16'>,
         <class 'numpy.int32'>,
         <class 'numpy.int64'>],
 'others': [<class 'bool'>,
            <class 'object'>,
            <class 'bytes'>,
            <class 'str'>,
            <class 'numpy.void'>],
 'uint': [<class 'numpy.uint8'>,
          <class 'numpy.uint16'>,
          <class 'numpy.uint32'>,
          <class 'numpy.uint64'>]}


## Reading an Writing to Files
Can use loadtxt or genfromtext to load data in an entire file into an array at once. Genfromtxt is more fault tolerant.
Use savetxt to write an array to a file

In [180]:
h=np.loadtxt('data.txt',skiprows=1,delimiter=",", dtype=np.int32)
print(h)
print(h.dtype)

np.savetxt('data2.txt', h, delimiter=',', fmt='%d', header='a;b;c;d;e;f;g;h;i;j', comments='')
#%d forces the stuff to be stored as integers. If we dont put comments equals nothing cuz otherwise header has hashtag...

[[9 3 8 7 6 1 0 4 2 5]
 [1 7 4 9 2 6 8 3 5 0]
 [4 8 3 9 5 7 2 6 0 1]
 [1 7 4 2 5 9 6 8 0 3]
 [0 7 5 2 8 6 3 4 1 9]
 [5 9 1 4 7 0 3 6 8 2]]
int32


In [181]:
h=np.genfromtxt('data.txt', skip_header=1, delimiter=',', dtype=np.int32)
print(h) #same thing as before

[[9 3 8 7 6 1 0 4 2 5]
 [1 7 4 9 2 6 8 3 5 0]
 [4 8 3 9 5 7 2 6 0 1]
 [1 7 4 2 5 9 6 8 0 3]
 [0 7 5 2 8 6 3 4 1 9]
 [5 9 1 4 7 0 3 6 8 2]]


## Mathematical Functions
You dont need to iterate (use for loops for every item in the array), you can apply an operation to an entire array or a slice of an array at once

In [182]:
print(h)
print(h>4)
print(h**2-1)

[[9 3 8 7 6 1 0 4 2 5]
 [1 7 4 9 2 6 8 3 5 0]
 [4 8 3 9 5 7 2 6 0 1]
 [1 7 4 2 5 9 6 8 0 3]
 [0 7 5 2 8 6 3 4 1 9]
 [5 9 1 4 7 0 3 6 8 2]]
[[ True False  True  True  True False False False False  True]
 [False  True False  True False  True  True False  True False]
 [False  True False  True  True  True False  True False False]
 [False  True False False  True  True  True  True False False]
 [False  True  True False  True  True False False False  True]
 [ True  True False False  True False False  True  True False]]
[[80  8 63 48 35  0 -1 15  3 24]
 [ 0 48 15 80  3 35 63  8 24 -1]
 [15 63  8 80 24 48  3 35 -1  0]
 [ 0 48 15  3 24 80 35 63 -1  8]
 [-1 48 24  3 63 35  8 15  0 80]
 [24 80  0 15 48 -1  8 35 63  3]]


In [188]:
print(h)
print(h.min())
print(h.max())
print(h.sum())
print(h.mean())
print(h.var())
print(h.std())

print(h.sum(axis=1))
print(h.min(axis=0))

print(h.argmin()) #getting the index of the min element
print(h.argmax()) #same for max element
# print(h.argsort()) doesnt really work consistently #creates a sorted array out of the specified array
h2=h.copy() #make a copy array of yours
h2.sort() #and then sort it
print(h2) #if you dont wana mutate the original

[[9 3 8 7 6 1 0 4 2 5]
 [1 7 4 9 2 6 8 3 5 0]
 [4 8 3 9 5 7 2 6 0 1]
 [1 7 4 2 5 9 6 8 0 3]
 [0 7 5 2 8 6 3 4 1 9]
 [5 9 1 4 7 0 3 6 8 2]]
0
9
270
4.5
8.25
2.8722813232690143
[45 45 45 45 45 45]
[0 3 1 2 2 0 0 3 0 0]
6
0
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


## Column Operations
Apply functions only to specific columns by slicing, or create a new array from the columns you want, then work on them.
But beware that creating a new pointer to the same data can screw your data up if youre not careful

In [106]:
print(h)
print(h[:, 2:3])
print(h[:, 2:3].max())

col3=h[:,3:4] #NOT a copy, just a pointer
print(col3)

col3*=100 #multiply and replace with result- modifies the array the pointer belongs to, directly!
print(h)

[[9 3 8 7 6 1 0 4 2 5]
 [1 7 4 9 2 6 8 3 5 0]
 [4 8 3 9 5 7 2 6 0 1]
 [1 7 4 2 5 9 6 8 0 3]
 [0 7 5 2 8 6 3 4 1 9]
 [5 9 1 4 7 0 3 6 8 2]]
[[8]
 [4]
 [3]
 [4]
 [5]
 [1]]
8
[[7]
 [9]
 [9]
 [2]
 [2]
 [4]]
[[  9   3   8 700   6   1   0   4   2   5]
 [  1   7   4 900   2   6   8   3   5   0]
 [  4   8   3 900   5   7   2   6   0   1]
 [  1   7   4 200   5   9   6   8   0   3]
 [  0   7   5 200   8   6   3   4   1   9]
 [  5   9   1 400   7   0   3   6   8   2]]


## Numpy Random Functions

In [117]:
np.set_printoptions(precision=5, suppress=True) #show 5dp, suppress scientific notation
i=np.random.random(6)
print(i)
print(i.dtype)

i=np.random.randint(10,99,8) #(low, high inclusive, size)
print(i)

np.random.shuffle(i) #in-place shuffle

print(np.random.choice(i))

i.sort() #in-place sort
print(i)

[0.58796 0.65987 0.85815 0.13726 0.78857 0.16106]
float64
[56 81 55 39 10 21 10 76]
76
[10 10 21 39 55 56 76 81]


In [189]:
print('\n') #enter...